# Generated by Django 5.2.1 on 2025-05-30 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cursodisciplina_periodo'),
    ]

    operations = [
    ]
